#GMail sample configuration
#May require a keystore for certificates
mailSender.protocol=${MAIL_PROTOCOL:smtps}
mailSender.host=${MAIL_HOST:smtp.gmail.com}
mailSender.port=${MAIL_PORT:465}
mailSender.username=${MAIL_USERNAME:}
mailSender.password=${MAIL_PASSWORD:}
mailSender.mail.smtp.auth=true
mail.smtp.starttls.enable=true